[package]
name = "mini_mmo_client"
version = "1.0.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
better_term = "*"
chrono = "*"
capnp = "*"
capnpc = "*"
toml = "*"